# Generated by Django 4.2.3 on 2023-07-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_bookmark_delete_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='article',
            new_name='post',
        ),
    ]
